# Generated by Django 5.2 on 2025-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
