# Generated by Django 5.2 on 2025-12-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_bus_capacity_alter_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='arrival_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_station_journeys', related_query_name='arrival_station_journeys', to='travel.station'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='departure_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_station_journeys', related_query_name='departure_station_journeys', to='travel.station'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_station_schedules', related_query_name='arrival_station_schedules', to='travel.station'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_station_schedules', related_query_name='departure_station_schedules', to='travel.station'),
        ),
    ]
