# Generated by Django 5.2 on 2025-12-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_user'),
        ('statement', '0002_alter_deposit_amount_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employees', to='statement.atm'),
        ),
    ]
