# Generated by Django 5.2 on 2025-12-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_atm'),
        ('post', '0012_parcel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', related_query_name='employees', to='post.postoffice'),
        ),
    ]
