# Generated by Django 5.2 on 2025-06-19 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('transfer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='client_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_client_receiver', to='transfer.client'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='client_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_client_sender', to='transfer.client'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_delivery_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postoffice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.city'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='inbox_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_inbox_mail', to='post.postoffice'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sent_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_send_mail', to='post.postoffice'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='inbox_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_inbox_mail', to='post.postoffice'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.city'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='sent_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_store', to='post.store'),
        ),
    ]
