# Generated by Django 5.2 on 2025-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
