# Generated by Django 5.2 on 2025-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_parcel_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='postage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='postage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
