# Generated by Django 5.2 on 2025-08-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_parcel_postage_alter_shopping_postage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='in_inbox_mail',
            field=models.BooleanField(default=False),
        ),
    ]
