# Generated by Django 5.2 on 2025-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_parcel_in_inbox_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='in_inbox_mail',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
