# Generated by Django 5.2 on 2025-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_parcel_parcel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='postage_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='product_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='seen_at',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='your_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
