# Generated by Django 5.2 on 2025-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_shopping_postage_price_shopping_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='seen_at',
            new_name='is_seen',
        ),
        migrations.AddField(
            model_name='shopping',
            name='message',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen'), ('rejected', 'Rejected'), ('resend', 'Resend'), ('done', 'Done')], default='unseen', max_length=10),
        ),
    ]
