# Generated by Django 5.2 on 2025-08-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_seen_at_shopping_is_seen_shopping_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
