# Generated by Django 5.2 on 2025-08-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_shopping_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='parcel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.parcel'),
        ),
    ]
