# Generated by Django 5.2 on 2025-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_shopping_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
