# Generated by Django 5.2 on 2025-12-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_parcel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', related_query_name='cities', to='post.governorate'),
        ),
    ]
