# Generated by Django 5.2 on 2025-12-01 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_city_governorate'),
        ('transfer', '0008_gift_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='client_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_receiver_parcels', related_query_name='client_receiver_parcels', to='transfer.client'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='client_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sender_parcels', related_query_name='client_sender_parcels', to='transfer.client'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_employee_parcels', related_query_name='delivery_employee_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='inbox_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_mail_parcels', related_query_name='inbox_mail_parcels', to='post.postoffice'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_employee_parcels', related_query_name='pickup_employee_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_receiver_parcels', related_query_name='user_receiver_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sender_parcels', related_query_name='user_sender_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sent_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_mail_parcels', related_query_name='send_mail_parcels', to='post.postoffice'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_employee_parcels', related_query_name='send_employee_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='inbox_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.postoffice'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='sent_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.store'),
        ),
    ]
