# Generated by Django 5.2 on 2025-12-01 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_parcel_client_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.governorate'),
        ),
    ]
