# Generated by Django 5.2 on 2026-01-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
