# Generated by Django 5.2 on 2026-01-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_item_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='display',
        ),
    ]
