# Generated by Django 5.2 on 2026-01-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_resturant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant',
            old_name='bussiness_hours',
            new_name='business_hours',
        ),
        migrations.AlterField(
            model_name='resturant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
