# Generated by Django 5.2 on 2025-08-18 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_directtransfer_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directtransfer',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
