# Generated by Django 5.2 on 2025-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_alter_directtransfer_amount_alter_fee_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='undirecttransfer',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
