# Generated by Django 5.2 on 2025-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_undirecttransfer_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtransfer',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
