# Generated by Django 5.2 on 2025-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_directtransfer_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
