# Generated by Django 5.2 on 2025-12-01 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_alter_deposit_customer_alter_deposit_user_and_more'),
        ('transfer', '0008_gift_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='directtransfer',
            name='delivery_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_employee_direct_transfers', related_query_name='delivery_employee_direct_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directtransfer',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer_direct_transfers', related_query_name='payer_direct_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gift',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payee_gifts', related_query_name='payee_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gift',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer_gifts', related_query_name='payer_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='delivery_atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_atm_undirect_transfers', related_query_name='delivery_atm_undirect_transfers', to='statement.atm'),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='delivery_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_employee_undirect_transfers', related_query_name='delivery_employee_undirect_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payee_undirect_transfers', related_query_name='payee_undirect_transfers', to='transfer.client'),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='payee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payee_user_undirect_transfers', related_query_name='payee_user_undirect_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer_undirect_transfers', related_query_name='payer_undirect_transfers', to='transfer.client'),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='transfer_atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_atm_undirect_transfers', related_query_name='transfer_atm_undirect_transfers', to='statement.atm'),
        ),
        migrations.AlterField(
            model_name='undirecttransfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_employee_undirect_transfers', related_query_name='transfer_employee_undirect_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
