"""
Django settings for travel_transfer project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
MY_DEPLOYMENT = True
MY_HTTPS = False

from pathlib import Path

import os  # new

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yz*ykwr!^n2hs&fbqk7y3mrg2(=(6sx7brb@4%g26bzfyq2c6%'

if MY_DEPLOYMENT:
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False

    ALLOWED_HOSTS = ["youshaa010yousef.pythonanywhere.com"]
else:
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    # ALLOWED_HOSTS = ["youshaa010yousef.pythonanywhere.com"]
    ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # new Required by allauth
    'django.contrib.sites',
    # new
    # apps
    'users',
    'profiles',
    'gallery',
    'travel',
    'transfer',
    'statement',
    'post',
    'notifications',
    'employees',
    'resturant',
    # 3rd party
    'rest_framework',
    'django_filters',
    # 'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'auth_kit',
    'corsheaders',
    'background_task',
]

if not MY_DEPLOYMENT and MY_HTTPS:
    INSTALLED_APPS += ['django_extensions']
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

"""
DUMP_DATA = [
gallery post.Governorate post.City post.PostOffice post.Store resturant statement.ATM transfer.Fee travel.Station travel.Bus travel.Journey travel.Schedule 
]
"""

# shell
# >>> from django.contrib.sites.models import Site
# >>> Site.objects.create(id=2, domain='localhost:8000', name='Localhost')
# new
if MY_DEPLOYMENT:
    SITE_ID = 3
else:
    SITE_ID = 2

# new
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication',
        'auth_kit.authentication.JWTCookieAuthentication' if MY_HTTPS else 'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        # 'rest_framework_xml.renderers.XMLRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # new
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination', 'PAGE_SIZE': 3,
}
if MY_HTTPS:
    REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'
# new
if MY_DEPLOYMENT and MY_HTTPS:
    AUTH_KIT = {
        "FRONTEND_BASE_URL": "https://youshaa010yousef.pythonanywhere.com",
        "USER_SERIALIZER": "users.serializers.UserSerializer",
        "REGISTER_EMAIL_CONFIRM_PATH": "verify/email",
        "PASSWORD_RESET_CONFIRM_PATH": "password/reset/confirm",
        "AUTH_COOKIE_SECURE": True,
        "AUTH_COOKIE_DOMAIN": "youshaa010yousef.pythonanywhere.com",
        "AUTH_JWT_COOKIE_PATH": '/api/',
        "AUTH_JWT_REFRESH_COOKIE_PATH": '/api/',

    }
elif (not MY_DEPLOYMENT) and MY_HTTPS:
    AUTH_KIT = {
        "FRONTEND_BASE_URL": "https://127.0.0.1:8000",
        "USER_SERIALIZER": "users.serializers.UserSerializer",
        "REGISTER_EMAIL_CONFIRM_PATH": "verify/email",
        "PASSWORD_RESET_CONFIRM_PATH": "password/reset/confirm",
        "AUTH_COOKIE_DOMAIN": "127.0.0.1",
        "AUTH_JWT_COOKIE_PATH": '/api/',
        "AUTH_JWT_REFRESH_COOKIE_PATH": '/api/',
        "AUTH_COOKIE_SECURE": True,
    }

# new
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=360),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=720),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # Enable token blacklisting
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# new
if not MY_DEPLOYMENT:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.mail.yahoo.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'youshaa010yousef@yahoo.com'
    EMAIL_HOST_PASSWORD = 'nwzjkzorxpybseyr'
    DEFAULT_FROM_EMAIL = 'Travel and Transfer <youshaa010yousef@yahoo.com>'

# new
if MY_DEPLOYMENT:
    # CORS_ORIGIN_WHITELIST = [
    #     'https://youshaa010yousef.pythonanywhere.com'
    # ]
    CORS_ALLOWED_ORIGINS = [
        'https://youshaa010yousef.pythonanywhere.com'
    ]
else:

    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'https://127.0.0.1:8000',
    ]

if MY_HTTPS:
    CORS_ALLOW_CREDENTIALS = True
    if My_DEPLOYMENT:
        CSRF_TRUSTED_ORIGINS = [
            'https://youshaa010yousef.pythonanywhere.com'
        ]
    else:
        CSRF_TRUSTED_ORIGINS = [
            'https://127.0.0.1:8000',
        ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # new
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware', # new
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travel_transfer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR ,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travel_transfer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if MY_DEPLOYMENT:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'youshaa010yousef$default',
            'USER': 'youshaa010yousef',
            'PASSWORD': 'UShaa010',
            'HOST': 'youshaa010yousef.mysql.pythonanywhere-services.com',
            'PORT': '3306',
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

TIME_ZONE = 'Asia/Damascus'

if MY_DEPLOYMENT:
    STATIC_URL = 'assets/'
    # new
    STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

else:
    STATIC_URL = 'assets/'
    # # new
    STATIC_ROOT = os.path.join(BASE_DIR, 'assets/')
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'assets/css'),
        os.path.join(BASE_DIR, 'assets/js'),
        os.path.join(BASE_DIR, 'templates'),
    ]

# new
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if MY_DEPLOYMENT:
    MY_URL = 'https://youshaa010yousef.pythonanywhere.com'
else:
    MY_URL = 'https://127.0.0.1:8000'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# new
AUTH_USER_MODEL = 'users.CustomUser'
