# Generated by Django 5.2 on 2025-12-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_gift_alter_notification_parcel_and_more'),
        ('post', '0012_parcel_is_paid'),
        ('transfer', '0008_gift_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='gift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.gift'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='parcel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.parcel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='undirect_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.undirecttransfer'),
        ),
    ]
